global:
  scrape_interval:     5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'loki'
    dns_sd_configs:
      - names:
          - read
          - write
          - backend
        type: A
        port: 3100